
package com.shippingdepartmentws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ShippingBean", targetNamespace = "www.shippingdepartmentws.com")
public interface ShippingBean {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "helloWorld", targetNamespace = "www.shippingdepartmentws.com", className = "com.shippingdepartmentws.HelloWorld")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "www.shippingdepartmentws.com", className = "com.shippingdepartmentws.HelloWorldResponse")
    public void helloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

}
