
package com.shippingdepartmentws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ShippingBeanService", targetNamespace = "www.shippingdepartmentws.com", wsdlLocation = "http://127.0.0.1:8080/ShippingDepartmentWS/ShippingBean?wsdl")
public class ShippingBeanService
    extends Service
{

    private final static URL SHIPPINGBEANSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.shippingdepartmentws.ShippingBeanService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.shippingdepartmentws.ShippingBeanService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/ShippingDepartmentWS/ShippingBean?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/ShippingDepartmentWS/ShippingBean?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SHIPPINGBEANSERVICE_WSDL_LOCATION = url;
    }

    public ShippingBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShippingBeanService() {
        super(SHIPPINGBEANSERVICE_WSDL_LOCATION, new QName("www.shippingdepartmentws.com", "ShippingBeanService"));
    }

    /**
     * 
     * @return
     *     returns ShippingBean
     */
    @WebEndpoint(name = "ShippingBeanPort")
    public ShippingBean getShippingBeanPort() {
        return super.getPort(new QName("www.shippingdepartmentws.com", "ShippingBeanPort"), ShippingBean.class);
    }

}
