
package com.camerasupplierws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "CameraSearchService", targetNamespace = "www.camerasupplierws.com", wsdlLocation = "http://127.0.0.1:8080/CameraSupplierWS/CameraSearch?wsdl")
public class CameraSearchService
    extends Service
{

    private final static URL CAMERASEARCHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.camerasupplierws.CameraSearchService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.camerasupplierws.CameraSearchService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/CameraSupplierWS/CameraSearch?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/CameraSupplierWS/CameraSearch?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CAMERASEARCHSERVICE_WSDL_LOCATION = url;
    }

    public CameraSearchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CameraSearchService() {
        super(CAMERASEARCHSERVICE_WSDL_LOCATION, new QName("www.camerasupplierws.com", "CameraSearchService"));
    }

    /**
     * 
     * @return
     *     returns CameraSearch
     */
    @WebEndpoint(name = "CameraSearchPort")
    public CameraSearch getCameraSearchPort() {
        return super.getPort(new QName("www.camerasupplierws.com", "CameraSearchPort"), CameraSearch.class);
    }

}
